name: Lines of Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lines of Code Badge
      uses: shadowmoose/GHA-LoC-Badge@1.0.0
      id: badge
      with:
        debug: true
        directory: .
        badge: ./output/badge.svg
        patterns: '*.md'  # Patterns in the format of a '.gitignore' file, separated by pipes.
        ignore: '.gitignore'
